### ISSUE TITLE
Download is not available

### ISSUE THREAD

**Issue by pedro-cf** [yannforget/landsatxplore#108]
Hello, trying to perform a simple download, which I can replicate in the webpage with https://earthexplorer.usgs.gov/download/632211e26883b1f7/LC92040332023207LGN00, but I am getting an error.

**My code:**

```python
from landsatxplore.earthexplorer import EarthExplorer

ee = EarthExplorer("***", "***")

ee.download('LC92040332023207LGN00', output_dir='./data')

ee.logout()
```

**Error:**
```bash
Download failed with dataset id 1 of 2. Re-trying with the next one.
None of the archived ids succeeded! Update necessary!
Traceback (most recent call last):
  File "/home/pedro/.local/lib/python3.10/site-packages/landsatxplore/earthexplorer.py", line 196, in download
    filename = self._download(
  File "/home/pedro/.local/lib/python3.10/site-packages/landsatxplore/earthexplorer.py", line 86, in _download
    raise EarthExplorerError(error_msg)
landsatxplore.errors.EarthExplorerError: Download is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/git/landsat_test/main.py", line 34, in <module>
    ee.download('LC92040332023207LGN00', output_dir='./data')
  File "/home/pedro/.local/lib/python3.10/site-packages/landsatxplore/earthexplorer.py", line 205, in download
    raise EarthExplorerError()
landsatxplore.errors.EarthExplorerError
```

**Comment by klimeto** [comment]
Hi @pedro-cf I am experiencing the same issues and the reason is that the version distributed via pip does not contain the latest commit: https://github.com/yannforget/landsatxplore/commit/20404a70ddd9c4982da49d5941a9ba44a7e830f6 which added new value to `DATA_PRODUCTS` list which  is used to extract `data_product_id` use in DW URL.

**Comment by mferraro-gh** [comment]
> Hi @pedro-cf I am experiencing the same issues and the reason is that the version distributed via pip does not contain the latest commit: [20404a7](https://github.com/yannforget/landsatxplore/commit/20404a70ddd9c4982da49d5941a9ba44a7e830f6) which added new value to `DATA_PRODUCTS` list which is used to extract `data_product_id` use in DW URL.

This issue still has not been fixed FYI!
