### ISSUE TITLE
download: EarthExplorerError: EE: login failed (csrf token not found).

### ISSUE THREAD

**Issue by landam** [yannforget/landsatxplore#18]
Download operation fails with 

```
landsatxplore.exceptions.EarthExplorerError: EE: login failed (csrf token not found).
```

Tested via API and command line tools. Note that search (LandsatAPI) works with the same username and password.

# Search

```
LANDSATXPLORE_USERNAME=XXX LANDSATXPLORE_PASSWORD=XXX landsatxplore search --dataset LANDSAT_TM_C1 --location 12.53 -1.53 \
>     --start 1995-01-01 --end 1995-12-31
LT51950511995123MPS00
LT51950511995139MPS00
LT51950511995155MPS00
LT51950511995171MPS00
LT51950511995203MPS00
LT51950511995219MPS00
```

# Download

```
LANDSATXPLORE_USERNAME=XXX LANDSATXPLORE_PASSWORD=XXX landsatxplore download LT51960471995178MPS00 
Traceback (most recent call last):
  File "/usr/local/bin/landsatxplore", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/landsatxplore/cli.py", line 96, in download
    ee = EarthExplorer(username, password)
  File "/usr/local/lib/python3.7/dist-packages/landsatxplore/earthexplorer.py", line 45, in __init__
    self.login(username, password)
  File "/usr/local/lib/python3.7/dist-packages/landsatxplore/earthexplorer.py", line 58, in login
    csrf, ncform = _get_tokens(rsp.text)
  File "/usr/local/lib/python3.7/dist-packages/landsatxplore/earthexplorer.py", line 32, in _get_tokens
    raise EarthExplorerError('EE: login failed (csrf token not found).')
landsatxplore.exceptions.EarthExplorerError: EE: login failed (csrf token not found).
```

# System Info

* Debian GNU/Linux stable
* Python 3.7.3
* landsatxplore 0.6 (pip)

**Comment by HanDuwol** [comment]
The name of csrf in the _get_tokens function in earthexplorer.py has been changed from'csrf_token' to'csrf'.

After modifying and trying, I log in normally, but the Download Url also seems to have changed.

`def _get_tokens(body):
    """Get `csrf_token` and `__ncforminfo`."""
    csrf = re.findall(r'name="csrf" value="(.+?)"', body)
    ncform = re.findall(r'name="__ncforminfo" value="(.+?)"', body)

    if not csrf:
        raise EarthExplorerError('EE: login failed (csrf token not found).')
    if not ncform:
        raise EarthExplorerError('EE: login failed (ncforminfo not found).')

    return csrf, ncform`

**Comment by yannforget** [comment]
Is this fixed in the last version (v.0.7) ? I cannot reproduce the issue.

**Comment by HanDuwol** [comment]
> Is this fixed in the last version (v.0.7) ? I cannot reproduce the issue.

I have experienced the problem, but applying v0.7 solved it!

**Comment by landam** [comment]
Great, thanks for the fix! Download now works.
