### ISSUE TITLE
KeyError: 'content-disposition'

### ISSUE THREAD

**Issue by Meresmata** [yannforget/landsatxplore#22]
Hi, 
 first first of all I want to express, that I now, that there is an issue with the swame title just thought the problem there, might be different.

I have some problems downloading data from the earth explorer. after a while the file didn't start to load down, this error is thrown:

>   0%|          | 0.00/341 [00:00<?, ?B/s]
> Traceback (most recent call last):
>   File "E:\___SVN\COP4EE-2\Landcover\Code\venv\lib\site-packages\landsatxplore\earthexplorer.py", line 77, in _download
>     local_filename = r.headers['Content-Disposition'].split('=')[-1]
>   File "E:\___SVN\COP4EE-2\Landcover\Code\venv\lib\site-packages\requests\structures.py", line 54, in __getitem__
>     return self._store[key.lower()][1]
> KeyError: 'content-disposition'

The code I use is:
```

for year, month in observation_period:
    # Request
    scenes = api.search(
        dataset='LANDSAT_8_C1',
        bbox=bbox,
        start_date=str(date(year, month, 1)),
        end_date=str(date(year, month, monthrange(year, month)[1])),
        max_cloud_cover=20)

    gdf = to_geodataframe(scenes).to_crs(32633).sort_values(by='cloudCover', ascending=True)
    filtered = filter_by_min_intersect(gdf, local_vector)

    save_path = Path(args.save_path) / str(year) / str(month)
    if not save_path.exists():
        makedirs(save_path)
    for entry, name in zip(filtered.entityId.values, filtered.displayId.values):
        if type(entry) == str:
            if name not in [x.stem.split(".")[0] for x in save_path.iterdir()]:
                print("Start loading {}.".format(name))
                ee.download(scene_id=entry, output_dir=save_path)

ee.logout()
api.logout()
```

**Comment by griembauer** [comment]
Hi @Meresmata, 
I have the same problem occasionally and so far could only trace it back to an issue on the Earth Explorer side. Trying to download the specific scenes from the browser client then also fails. However, after some time the download works successfully, both via client and landsatxplore.
Best,
Guido

**Comment by yannforget** [comment]
`EarthExplorerError: Data not available` is now raised if the issue is from Earth Explorer (or `TimeoutError` if there isn't any response).

**Comment by ChangpeiHe** [comment]
so, did you have solved this problem?
