### ISSUE TITLE
Download fails 

### ISSUE THREAD

**Issue by henrykironde** [yannforget/landsatxplore#67]
```python
(env) ➜  usgs-test landsatxplore search --dataset landsat_ot_c2_l2 --location 31.9378 -109.0803  --start 2021-09-01 --end 2022-02-02
LC08_L2SP_035038_20220120_20220127_02_T1
LC08_L2SP_034038_20220113_20220123_02_T1
LC08_L2SP_035038_20220104_20220113_02_T1
LC08_L2SP_034038_20211228_20220105_02_T1
LC08_L2SP_035038_20211219_20211223_02_T1
LC08_L2SP_034038_20211212_20211222_02_T1
LC08_L2SP_035038_20211203_20211209_02_T1
LC08_L2SP_034038_20211126_20211201_02_T1
LC08_L2SP_035038_20211117_20211125_02_T1
LC08_L2SP_034038_20211110_20211117_02_T1
LC08_L2SP_035038_20211101_20211109_02_T1
LC08_L2SP_034038_20211025_20211103_02_T1
LC08_L2SP_035038_20211016_20211026_02_T1
LC08_L2SP_034038_20211009_20211019_02_T1
LC08_L2SP_035038_20210930_20211013_02_T1
LC08_L2SP_035038_20210914_20210924_02_T1
LC08_L2SP_034038_20210907_20210916_02_T1
```
```python
(env) ➜  usgs-test landsatxplore download LC08_L2SP_035038_20210914_20210924_02_T1                                                 
Traceback (most recent call last):
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/bin/landsatxplore", line 10, in <module>
    sys.exit(cli())
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/landsatxplore/cli.py", line 165, in download
    scene, output_dir, dataset=dataset, timeout=timeout, skip=skip
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/landsatxplore/earthexplorer.py", line 150, in download
    filename = self._download(url, output_dir, timeout=timeout, skip=skip)
  File "/Users/henrykironde/Documents/GitHub/python-virtual-environments/env/lib/python3.7/site-packages/landsatxplore/earthexplorer.py", line 92, in _download
    raise EarthExplorerError(error_msg)
landsatxplore.errors.EarthExplorerError: Download is not available
```

**Comment by dengshuaix** [comment]
Hi, I also encountered this problem, dataset: landsat_ot_c2_l1 . How did you solve it?

**Comment by lukecarberry** [comment]
I am also experiencing this. Hope there is a solution!

**Comment by HanDuwol** [comment]
I think I solved it!
I modified the next code for earthexplorer.py!

`# IDs of GeoTIFF data product for each dataset
DATA_PRODUCTS = {
    "landsat_tm_c1": "5e83d08fd9932768",
    "landsat_etm_c1": "5e83a507d6aaa3db",
    "landsat_8_c1": "5e83d0b84df8d8c2",
    "landsat_tm_c2_l1": "5e83d0a0f94d7d8d",
    "landsat_etm_c2_l1": "5e83d0d0d2aaa488",
    # "landsat_ot_c2_l1": "5e81f14ff4f9941c",
    "landsat_ot_c2_l1": "5e81f14f92acf9ef",
    "landsat_tm_c2_l2": "5e83d11933473426",
    "landsat_etm_c2_l2": "5e83d12aada2e3c5",
    "landsat_ot_c2_l2": "5e83d14f30ea90a9",
    
    
    "sentinel_2a": "5e83a42c6eba8084",
}`

USGS's earthhexplorer, web developer, analyzed the network with tools to find a difference!

**Comment by henrykironde** [comment]
Thanks @HanDuwol will try it out.

**Comment by Jomigal** [comment]
Hi, everyone
It seems that datasetId for 'landsat_ot_c2_l1 is changed again because i tried with the datasetID propoused by @HanDuwol but it doesn't work. Did anyone know how to solve this again?

Thanks

**Comment by HanDuwol** [comment]
> Hi, everyone It seems that datasetId for 'landsat_ot_c2_l1 is changed again because i tried with the datasetID propoused by @HanDuwol but it doesn't work. Did anyone know how to solve this again?
> 
> Thanks
> 
> I found this datasetID: 5e81f14f59432a27 and change it but the answer obtained is " Unable to find product configuration"
> 
> In other hand trying to find out the download link for one simple image i found that download link provided is:
> 
> https://dds.cr.usgs.gov/download/eyJpZCI6MTQ5NjY3NzU3LCJjb250YWN0SWQiOjE0MzQ2Mjh9/
> 
> which is tottally different to provided in Earthexplorer.py

I checked it today and it seems to have been changed.  It would be better to check the ㅇㅁdatasetID with the datasetName with dataset-search api rather than hardcoding the datasetID.

**Comment by lukecarberry** [comment]
@HanDuwol Could you explain what you mean? Or provide an example? I don't know how to do what you're saying here. Thanks!
