### ISSUE TITLE
API does not work!

### ISSUE THREAD

**Issue by AmirM69** [yannforget/landsatxplore#80]
Does anyone know why this error below occurs to me, when I try to create an instance of API using my EROS username and password?
The ErathExplorer website is not down and I recently got machine-to-machine access.

my code:
`api = API('username', 'pass')`

error:
> Traceback (most recent call last):
  File "C:\Users\landsat_batch_download.py", line 67, in <module>
    api = API("https://m2m.cr.usgs.gov/api/api/json/stable/",'username', 'pass')
  File "C:\Users\Anaconda3\envs\lbd\lib\site-packages\landsatxplore\api.py", line 28, in __init__
    self.key = self.login(username, password)
  File "C:\Users\Anaconda3\envs\lbd\lib\site-packages\landsatxplore\api.py", line 48, in login
    response = requests.post(self.endpoint + 'login?', data=data).json()
  File "C:\Users\Anaconda3\envs\lbd\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Anaconda3\envs\lbd\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Anaconda3\envs\lbd\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Anaconda3\envs\lbd\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by SergioFerrerSanchez** [comment]
I solved using python 3.9 and installing running again 
`pip install landsatxplore`
