### ISSUE TITLE
Download does not seem to work

### ISSUE THREAD

**Issue by henrykironde** [yannforget/landsatxplore#82]
landsatxplore download -u $username -p $password LC09_L1TP_035038_20220707_20220707_02_T1

It looks like the login is not working when downloading but works fine when searching.

```Python 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/retriever3.8/bin/landsatxplore", line 8, in <module>
    sys.exit(cli())
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/landsatxplore/cli.py", line 157, in download
    ee = EarthExplorer(username, password)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/landsatxplore/earthexplorer.py", line 55, in __init__
    self.login(username, password)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/landsatxplore/earthexplorer.py", line 66, in login
    csrf, ncform = _get_tokens(rsp.text)
  File "/opt/miniconda3/envs/retriever3.8/lib/python3.8/site-packages/landsatxplore/earthexplorer.py", line 39, in _get_tokens
    ncform = re.findall(r'name="__ncforminfo" value="(.+?)"', body)[0]
IndexError: list index out of range
```

**Comment by jeronimoluza** [comment]
Same issue here! Any chance they changed something during the system maintenance?

**Comment by henrykironde** [comment]
I believe so. They always change the platform, and it always results in backwards compatibility issues. This is true for the API they provide,

the `usgs-machine-to-machine-API`, which now fails with the same error.

`INPUT_PARAMETER_INVALID -  Scene list does not contain any valid scenes`

**Comment by henrykironde** [comment]
An update on this: there are some changes on the scene list at https://earthexplorer.usgs.gov/order/index/. You need to sign in. It looks like you will need to order them from the website. The [Machine-to-Machine (M2M) API](https://m2m.cr.usgs.gov/) doesn't seem updated. Hope it's not more manual work than it is currently.

**Comment by qk1997** [comment]
hi,Did you solve the problem？

**Comment by MahdiFakouri** [comment]
hi,Did you solve the problem？

**Comment by henrykironde** [comment]
Not yet solved

**Comment by ahsouri** [comment]
This is a crucial problem that makes this beautiful tool literally unusable. Any suggestion by the developer @yannforget?

**Comment by legendjslc** [comment]
I have the same problem.

**Comment by legendjslc** [comment]
I think just remove ncform in function get_token, it will work. 
`
def _get_tokens(body):
    """Get `csrf_token` and `__ncforminfo`."""
    csrf = re.findall(r'name="csrf" value="(.+?)"', body)[0]
    ncform = re.findall(r'name="__ncforminfo" value="(.+?)"', body)[0]
`

**Comment by haozhen315** [comment]
> I think just remove ncform in function get_token, it will work. `def _get_tokens(body): """Get`csrf_token`and`__ncforminfo`.""" csrf = re.findall(r'name="csrf" value="(.+?)"', body)[0] ncform = re.findall(r'name="__ncforminfo" value="(.+?)"', body)[0] `

yes it works!

just change function _get_tokens to:

def _get_tokens(body):
    """Get `csrf_token` and `__ncforminfo`."""
    csrf = re.findall(r'name="csrf" value="(.+?)"', body)[0]
    # ncform = re.findall(r'name="__ncforminfo" value="(.+?)"', body)[0]

    if not csrf:
        raise EarthExplorerError("EE: login failed (csrf token not found).")
    # if not ncform:
    #     raise EarthExplorerError("EE: login failed (ncforminfo not found).")

    ncform = None
    return csrf, ncform

now I am able to download successfully.

but why is this?

**Comment by zgcao** [comment]
The issue of tokens can be solved as suggested. 

But my terminal gave an new expection:

`  File "C:\Users\zcao\miniconda3\envs\landsat\lib\site-packages\landsatxplore\earthexplorer.py", line 151, in download
    filename = self._download(url, output_dir, timeout=timeout, skip=skip)
  File "C:\Users\zcao\miniconda3\envs\landsat\lib\site-packages\landsatxplore\earthexplorer.py", line 104, in _download
    local_filename = r.headers["Content-Disposition"].split("=")[-1]
  File "C:\Users\zcao\miniconda3\envs\landsat\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'`

Did you have same issue now? If yes, it seems that the header format has been changed, we need make more a little bit customized settings.

**Comment by tvoirand** [comment]
Hi,
I encountered the same issue today.
It seems this issue is fixed by @jcintasr PR https://github.com/yannforget/landsatxplore/pull/75.
